apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: netpulse-prom
    access: proxy
    url: http://172.20.20.102:9090
    isDefault: true
    jsonData:
      timeInterval: 1s
